# os_singleNode_2.yml

kind: Service
apiVersion: v1
metadata:
  name: os
  labels:
    app: opensearch
spec:
  clusterIP: None
  ports:
    - port: 9300
      name: inter-node
    - port: 9200
      name: rest
  selector:
    app: opensearch

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: os-master
spec:
  serviceName: os
  replicas: 1
  selector:
    matchLabels:
      app: opensearch # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.6.0
        # imagePullPolicy: Always
        resources:
            limits:
              cpu: 2
            requests:
              cpu: 1
        ports:
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        - containerPort: 9200
          name: rest
          protocol: TCP
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: node.name
            value: $(HOSTNAME).os.default.svc.cluster.local
          - name: network.host
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: cluster.name
            value: os-cluster-1
          - name: cluster.initial_master_nodes
            value: "os-master-0.os.default.svc.cluster.local"
          - name: discovery.seed_hosts
            value: "os-master-0.os.default.svc.cluster.local" #csv values of every master. ,os-master-1.os.default.svc.cluster.local,os-master-2.os.default.svc.cluster.local
          - name: node.master
            value: "true"
          - name: node.data
            value: "false"
          - name: ES_JAVA_OPTS
            value: "-Xms4G -Xmx4G"